### PR TITLE
Add "Access-Control-Allow-Headers"

### PR DESCRIPTION
**Pull request by einstein95**

### CODE REVIEW

**Comment by tomysshadow** [comment]
I'm not certain what this header does, although I'm sure you guys already discussed why it'd be a good idea to add. Do you think support for Access-Control-Allow-Methods should be added too? Seems related
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods

**Comment by einstein95** [comment]
The header is at least required by HTML5 games that send an OPTIONS request with eg an `authorization` method and want to know if it's supported by the server. Basically adding it removes the need for a hack for some CN games that access a different domain for profile details

**Comment by tomysshadow** [comment]
K. Let me know if it'd be a good idea to also add Access-Control-Allow-Methods, and I'll merge the pull request.

**Comment by einstein95** [comment]
I don't see how it'd be a bad idea

**Comment by tomysshadow** [comment]
K. I will merge the change and also add the other header.

**Pull request merged**
